apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: qa-pipeline
  name: qa-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/Estafet-LTD/estafet-microservices-scrum-qa"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: qa-pipeline.groovy
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic    
status:
  lastVersion: 0